### ISSUE TITLE
Fix Profile Page of other users 

### ISSUE THREAD

**Issue by melengmoshokoa** [COS301-SE-2024/MovieHub#241]
Fix the follow button and posts of other users

**Comment by melengmoshokoa** [comment]
ensuring like button is red if post/review was liked 
follow button should say the correct state 
number of followers and following 
people following and that are followers are all that is left to do

**Comment by ZandileModise** [comment]
Done

**Comment by ZandileModise** [comment]
Fixing the followers/following pages

**Comment by ZandileModise** [comment]
Done
