### ISSUE TITLE
Watchlist private/public

### ISSUE THREAD

**Issue by CharlizeHanekom** [COS301-SE-2024/MovieHub#376]
Not sure that this is integrated. The edit watchlist is a problem, but I think in createWatchlist, private/public isn't being stored

@Jayson22571532

**Comment by ZandileModise** [comment]
Watchlists are viewed as public/private problem was with toggle which viewed them vice versa. Will have to just update Joyce @melengmoshokoa i have noticed that on the home page we fetch private instead of public watchlists

**Comment by Jayson22571532** [comment]
I belive i fixed this issue every where on dev As well as adding a check when fetching for another users profile to see if it's public or private

**Comment by ZandileModise** [comment]
Fixed as stated above
